@extends('layouts.codigoRegistroSubasta')
@section('tablaTipos')
<table  id="tablaAnimales"  style="width: 100%;background-color: whitesmoke">
    <thead>                
        <tr style=>
            <th class="active" colspan="2" style="background-color: palegoldenrod">Tipos de Animales</th>                    
        </tr>
        <tr>                    
            <th>Codigo</th>
            <th>Descripcion</th>  
        </tr>
    </thead>
    <tbody style="background-color: whitesmoke">
        <tr>
            <td>01</td>
            <td>Toro</td>
        </tr>
        <tr>
            <td>02</td>
            <td>Vaca</td>
        </tr>
        <tr>
            <td>03</td>
            <td>Camello</td>
        </tr>
        <tr>
            <td>04</td>
            <td>Toro</td>
        </tr>
        <tr>
            <td>05</td>
            <td>Vaca</td>
        </tr>
        <tr>
            <td>06</td>
            <td>Camello</td>
        </tr>
        <tr>
            <td>07</td>
            <td>Toro</td>
        </tr>
        <tr>
            <td>08</td>
            <td>Vaca</td>
        </tr>
        <tr>
            <td>09</td>
            <td>Camello</td>
        </tr>
        <tr>
            <td>10</td>
            <td>Vaca</td>
        </tr>
        <tr>
            <td>11</td>
            <td>Camello</td>
        </tr>
        <tr>
            <td>12</td>
            <td>Camello</td>
        </tr>

    </tbody>
</table>
<table id="tablaColores" style="width: 100%;background-color:whitesmoke " >
    <thead>                
        <tr>
            <th colspan="2" style="background-color: palegoldenrod">Colores de Animales</th>                    
        </tr>
        <tr>                    
            <th>Codigo</th>
            <th>Color</th>  
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>01</td>
            <td>Amarillo</td>
        </tr>
        <tr>
            <td>02</td>
            <td>Verde</td>
        </tr>
        <tr>
            <td>03</td>
            <td>Rojo</td>
        </tr>
        <tr>
            <td>04</td>
            <td>Amarillo</td>
        </tr>
        <tr>
            <td>05</td>
            <td>Verde</td>
        </tr>
        <tr>
            <td>06</td>
            <td>Rojo</td>
        </tr>
        <tr>
            <td>07</td>
            <td>Amarillo</td>
        </tr>
        <tr>
            <td>08</td>
            <td>Verde</td>
        </tr>
        <tr>
            <td>09</td>
            <td>Rojo</td>
        </tr>

    </tbody>
</table>    
@endsection